import Vue from 'vue'
import {
  Area,
  Button,
  Card,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  CountDown,
  DatetimePicker,
  Field,
  Form,
  Grid,
  GridItem,
  Icon,
  List,
  NavBar,
  Popup,
  PullRefresh,
  SwipeCell,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Calendar,
  ActionSheet,
  Col,
  Row,
  Divider,
  Radio,
  RadioGroup,
  Picker,
  Uploader,
  Collapse,
  CollapseItem,
  Toast,
  Image as VanImage,
  Lazyload,
  Loading,
  NoticeBar,
  Empty,
  Search,
  Step,
  Steps,
} from 'vant'

Vue.use(Button)
Vue.use(Cell)
Vue.use(List)
Vue.use(Tabbar).use(TabbarItem).use(CountDown).use(Grid).use(GridItem).use(Toast).use(Field).use(CellGroup).use(NavBar).use(SwipeCell).use(Card).use(Form).use(Popup).use(Area).use(Checkbox).use(CheckboxGroup).use(Icon).use(Tab).use(Tabs).use(DatetimePicker).use(PullRefresh).use(Calendar).use(ActionSheet).use(Col).use(Row).use(Divider).use(Radio).use(RadioGroup).use(Picker).use(Uploader).use(Collapse).use(CollapseItem).use(VanImage).use(Lazyload).use(Loading).use(NoticeBar).use(Empty).use(Search).use(Step).use(Steps)
